== Pesquisa Bibliográfica

:cap: cap2
:img: images/{cap}

[quote, Samuel Johnson]
____
``Há conhecimento de dois tipos: sabemos
sobre um assunto, ou sabemos onde podemos
buscar informação sobre ele.''
____

=== Leitura de Artigo Científico

Ao ler um artigo científico é preciso fazê-lo com:


- Foco,
- Metodologia,
- Criticismo,
- Criando seu próprio método, e
- Em busca de oportunidades de pesquisa.

=== Estruturação de Artigo Científico

Um artigo científico pode/deve conter as seguintes seções:

1. Título;
2. Informações sobre autores e sua filiação (instituição);
3. Resumo/Abstract (em língua estrangeira);
4. Palavras-chave;
5. Introdução;
6. Revisão Bibliográfica/Conceituação/Fundamentação Teórica;
7. Apresentação do trabalho científico (abordagem/metodologia/estudo
comparativo/);
8. Apresentação da metodologia utilizada na pesquisa;
9. Validação do trabalho científico: estudo de caso, experimentos, prova
de conceito, etc.;
10. Trabalhos Relacionados;
11. Trabalhos Futuros;
12. Conclusões;
13. Referências; e
14. Agradecimentos.

=== Pesquisa Bibliográfica

_Wikis_ (como a _Wikipedia_) são úteis e interessantes, mas não são
exatamente fontes científicas. _Wikis_ servem como ponto de partida para uma
pesquisa sobre determinado tema. Para uma pesquisa mais aprofundada, que o rigor
científico exige, é necessário pesquisar por artigos científicos.
Alguns engenhos de busca científicos são os listados a seguir:


* CiteSeerX (Scientific Literature Digital Library and Search
Engine) -- link:http://citeseerx.ist.psu.edu[]

* Google Scholar (Google Acadêmico) -- link:http://scholar.google.com.br[]

* Microsoft Academic Search -- link:http://academic.research.microsoft.com/[]

Outras fontes úteis são os portais, tais como:


* Periódicos da CAPES -- link:http://www.periodicos.capes.gov.br[]

* Lecture Notes in Computer Science -- link:http://www.springer.com/computer/lncs?SGWID=0-164-0-0-0[]

* IEEE (Institute of Electrical and Electronics Engineers) Publications and Standards -- link:http://www.ieee.org/publications_standards/index.html[]

* ACM (Association for Computer Machinery) -- link:http://www.acm.org/publications[]

=== Avaliação de Artigos Científicos

Existem muitas publicações de artigos, tanto nacionais como internacionais, em: 

- Conferências,
- Simpósios,
- Workshops, e
- Revistas (Journals).

A questão é, como avaliá-las?

No Brasil, a CAPES (http://www.capes.gov.br) realiza uma avaliação
denominada Qualisfootnote:[Link da Qualis: link:http://www.capes.gov.br/avaliacao/qualis[]].  
Internacionalmente tem-se o Fator de Impacto (Impact Factor), como uma
medida que reflete o número médio de citações de artigos publicados.
Artigos em publicações com maior fator de impacto são em geral
considerados pela comunidade científica, como artigos de melhor
``qualidade''. Entretanto qualidade pode exigir uma avaliação mais
subjetiva. Assim, estes índices Qualis ou Fator de Impacto, são guias
que dão boas noções de avaliação, mas não são determinantes.

=== Atividades

==== Atividade 1

Ler o artigo “Grandes Desafios da Computação” (versão português) que
encontra-se disponível em: link:http://goo.gl/3cEcnf[].

Os desafios mencionados são:

1. Gestão da informação em grandes volumes de dados multimídia
distribuídos,
2. Modelagem computacional de sistemas complexos artificiais, naturais
e sócio-culturais e da interação homem-natureza,
3. Impactos para a área da computação da transição do silício para
novas tecnologias,
4. Acesso participativo e universal do cidadão brasileiro ao conhecimento,
5. Desenvolvimento tecnológico de qualidade: sistemas disponíveis,
corretos, seguros, escaláveis, persistentes e ubíquos.

O aluno deverá escolher um dos desafios discutidos no artigo para:

- Ler, e fazer um resumo

==== Atividade 2 (Opcional)

Acesse até portal de periódicos da CAPES (a UFPB tem acesso ao
conteúdo):

.Portal de Periódicos da CAPES: link:http://www.periodicos.capes.gov.br[]
image::{img}/periodicos.eps[]

O aluno deve realizar as seguintes atividades:

- Navegar pelo portal para obter informação e se familiarizar;
- Descrever como o portal está organizado em termos de
estrutura, conteúdo, etc.
